# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: 'echo "This is test file for hmc" > file2.txt'
- task: CmdLine@2
  inputs:
    script: 'cat file2.txt'
- task: CmdLine@2
  displayName: Test_append
  inputs:
    script: |
      echo '$(Build.ArtifactStagingDirectory)' > workspace
      cat workspace >>file2.txt
- task: CmdLine@2
  inputs:
    script: |
      cd $(Build.ArtifactStagingDirectory)
      ls -la
- task: CmdLine@2
  inputs:
    script: |
      pwd
      ls -la
      cat file2.txt
- task: CmdLine@2
  inputs:
    script: |
      chmod +x validation.sh
      ./validation.sh
- task: CmdLine@2
  inputs:
    script: |
      cd $(Agent.BuildDirectory)/a
      ls -la
      cd $(Agent.BuildDirectory)/b
      ls -la
      cd $(Agent.BuildDirectory)/s
      ls -la
- task: CmdLine@2
  inputs:
    script: 'cat $(Agent.BuildDirectory)/s/script/tfile'
- task: CmdLine@2
  displayName: Working directory  
  inputs:
    script: |
      cd $(Agent.WorkFolder)
      pwd
      ls -la
- task: CopyFiles@2
  displayName: CopyFiles-Task
  inputs:
    SourceFolder: 
    Contents: '**'
    TargetFolder: '$(Build.SourceDirectory)/b'
- task: CmdLine@2
  inputs:
    script: |
      cd $(Build.SourceDirectory)/b
      ls -la