# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: 'echo "This is test file for hmc" > /home/vsts/work/1/s/file2.txt'
- task: CmdLine@2
  inputs:
    script: 'cat file2.txt'
- task: CmdLine@2
  displayName: Test_append
  inputs:
    script: |
      echo '$(Build.ArtifactStagingDirectory)' > workspace
      cat workspace >>file2.txt
- task: CmdLine@2
  inputs:
    script: |
      cd $(Build.ArtifactStagingDirectory)
      ls -la
- task: CmdLine@2
  inputs:
    script: |
      pwd
      ls -la
      cat file2.txt
- task: CmdLine@2
  inputs:
    script: |
      chmod +x validation.sh
      ./validation.sh
- task: CmdLine@2
  inputs:
    script: 'cat /home/vsts/work/1/s/script/tfile'
