# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: creating a file
  inputs:
    targetType: 'inline'
    script: 'echo "hello this is inline text" > file2.txt'
- task: Reading content in file
  inputs:
    targetType: 'inline'
    script: 'cat file2.txt'