# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "my name is ramesh"
  displayName: 'Print the name'

- script: echo $whoami > genfile.txt
  displayName: 'writing content in file'
